--- #YAML:1.0
name:               Tie-StoredOrderHash
version:            0.21
abstract:           ordered associative arrays for Perl
author:
    - tom murtagh <cpan@notto.be>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
